name: Youtube_Downloader

on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl stop youtube_dl
            cd ~/Youtube_Downloader
            git pull
            systemctl start youtube_dl
